In [15]:
import numpy as np
import pandas as pd
from collections import Counter
from sklearn.model_selection import train_test_split 
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix , classification_report



In [16]:
data = pd.read_csv('emails.csv')
data=data.drop('Email No.', axis=1)
data.head(10)


the  to  ect  and  for  of    a  you  hou  in  ...  connevey  jay  valued  \
0    0   0    1    0    0   0    2    0    0   0  ...         0    0       0   
1    8  13   24    6    6   2  102    1   27  18  ...         0    0       0   
2    0   0    1    0    0   0    8    0    0   4  ...         0    0       0   
3    0   5   22    0    5   1   51    2   10   1  ...         0    0       0   
4    7   6   17    1    5   2   57    0    9   3  ...         0    0       0   
5    4   5    1    4    2   3   45    1    0  16  ...         0    0       0   
6    5   3    1    3    2   1   37    0    0   9  ...         0    0       0   
7    0   2    2    3    1   2   21    6    0   2  ...         0    0       0   
8    2   2    3    0    0   1   18    0    0   3  ...         0    0       0   
9    4   4   35    0    1   0   49    1   16   9  ...         0    0       0   

   lay  infrastructure  military  allowing  ff  dry  Prediction  
0    0               0         0         0   0    0           0  
1    0               0         0         0   1    0           0  
2    0               0         0         0   0    0           0  
3    0               0         0         0   0    0           0  
4    0               0         0         0   1    0           0  
5    0               0         0         0   0    0           1  
6    0               0         0         0   0    0           0  
7    0               0         0         0   1    0           1  
8    0               0         0         0   0    0           0  
9    0               0         0         0   0    0           0  

[10 rows x 3001 columns]

In [17]:
X=data.iloc[:,:-1].values
Y=data.iloc[:,-1].values

In [18]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

class LogisticRegression():

    def __init__(self, lr=0.001, n_iters=1000):
        self.lr = lr
        self.n_iters = n_iters
        self.weights = None
        self.bias = None

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0

        for _ in range(self.n_iters):
            linear_pred = np.dot(X, self.weights) + self.bias
            predictions = sigmoid(linear_pred)

            dw = (1/n_samples) * np.dot(X.T, (predictions - y))
            db = (1/n_samples) * np.sum(predictions-y)

            self.weights = self.weights - self.lr*dw
            self.bias = self.bias - self.lr*db


    def predict(self, X):
        linear_pred = np.dot(X, self.weights) + self.bias
        y_pred = sigmoid(linear_pred)
        class_pred = [0 if y<=0.5 else 1 for y in y_pred]
        return class_pred

In [19]:
indices=list(range(len(Y)))
k_folds=5
folds=np.array_split(indices,k_folds)
for f_idx in range (k_folds):
    test_folds=folds[f_idx]
    train_folds=np.concatenate(np.delete(folds,f_idx,axis=0))
    X_train,X_test,Y_train,Y_test=X[train_folds],X[test_folds],Y[train_folds],Y[test_folds]
    ##fitting the model
    clf = LogisticRegression(lr=0.01)
    clf.fit(X_train,Y_train) # calling the fit function from LogisticRegression class
    y_pred = clf.predict(X_test) # calling the predict function from LogisticRegression class
    
    print(classification_report(Y_test,  y_pred))
    cm = confusion_matrix(Y_test, y_pred)
    print(cm)

C:\Users\Subham Sabud\AppData\Local\Temp\ipykernel_22876\1278053100.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


              precision    recall  f1-score   support

           0       0.92      0.96      0.94       715
           1       0.88      0.80      0.84       285

    accuracy                           0.91      1000
   macro avg       0.90      0.88      0.89      1000
weighted avg       0.91      0.91      0.91      1000

[[685  30]
 [ 56 229]]


C:\Users\Subham Sabud\AppData\Local\Temp\ipykernel_22876\1278053100.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


              precision    recall  f1-score   support

           0       0.92      0.94      0.93       723
           1       0.83      0.79      0.81       277

    accuracy                           0.90      1000
   macro avg       0.88      0.86      0.87      1000
weighted avg       0.90      0.90      0.90      1000

[[679  44]
 [ 59 218]]


C:\Users\Subham Sabud\AppData\Local\Temp\ipykernel_22876\1278053100.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


              precision    recall  f1-score   support

           0       0.88      0.97      0.92       716
           1       0.90      0.67      0.76       284

    accuracy                           0.88      1000
   macro avg       0.89      0.82      0.84      1000
weighted avg       0.88      0.88      0.88      1000

[[694  22]
 [ 95 189]]


C:\Users\Subham Sabud\AppData\Local\Temp\ipykernel_22876\1278053100.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


              precision    recall  f1-score   support

           0       0.80      0.99      0.89       706
           1       0.93      0.42      0.58       294

    accuracy                           0.82      1000
   macro avg       0.86      0.70      0.73      1000
weighted avg       0.84      0.82      0.80      1000

[[696  10]
 [170 124]]


C:\Users\Subham Sabud\AppData\Local\Temp\ipykernel_22876\1278053100.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


              precision    recall  f1-score   support

           0       0.87      0.92      0.90       694
           1       0.79      0.70      0.74       306

    accuracy                           0.85      1000
   macro avg       0.83      0.81      0.82      1000
weighted avg       0.85      0.85      0.85      1000

[[638  56]
 [ 93 213]]
